Document: tmux
Title: Debian tmux Manual
Author: <insert document author here>
Abstract: This manual describes what tmux is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tmux/tmux.sgml.gz

Format: postscript
Files: /usr/share/doc/tmux/tmux.ps.gz

Format: text
Files: /usr/share/doc/tmux/tmux.text.gz

Format: HTML
Index: /usr/share/doc/tmux/html/index.html
Files: /usr/share/doc/tmux/html/*.html
